name: Monitor Politico Diario

on:
  schedule:
    - cron: '15 23,12 * * *' #Corre a las 12:00 UTC (09:00 de Argentina) y a las 00:00 UTC (21:00 de Argentina)a
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    env: # <--- ACÁ ESTÁ EL CAMBIO (Silencia el aviso de Node 20)
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar librerias
        run: pip install -r requirements.txt

      - name: Ejecutar Robot
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          TWITTERAPI_KEY: ${{ secrets.TWITTERAPI_KEY }}
          OPENARG_API_KEY: ${{ secrets.OPENARG_API_KEY }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        run: python main.py

      - name: Guardar resultados en el repositorio
        if: always()
        run: |
          git config --local user.email "bot@github.com"
          git config --local user.name "Observatorio Bot"
          git add data/*.json radar_federal.db
          git commit -m "Actualizacion diaria: $(date +'%Y-%m-%d') [skip ci]" || echo "Sin cambios nuevos"
          git pull --rebase origin main
          git push
